# -*- coding: utf-8 -*-
"""Fine_tune_SAM_myocardium_autobounding_box.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxUsIERa_ekDKSpAC6rgA62BuqRkl98Y

# Notebook: fine-tune SAM (segment anything) on a custom dataset

In this notebook, we'll reproduce the [MedSAM](https://github.com/bowang-lab/MedSAM) project, which fine-tunes [SAM](https://huggingface.co/docs/transformers/main/en/model_doc/sam) on a dataset of medical images. For demo purposes, we'll use a toy dataset, but this can easily be scaled up.

Resources used to create this notebook (thanks 🙏):
* [Encode blog post](https://encord.com/blog/learn-how-to-fine-tune-the-segment-anything-model-sam/)
* [MedSAM repository](https://github.com/bowang-lab/MedSAM).

## Set-up environment

We first install 🤗 Transformers and 🤗 Datasets.

## Dataset

This model was trained on 144 images and masks from the "shriya/myocardium_segmentation_expanded" dataset repository. All images were resized to 256 by 256
"""

"""#Set up environment"""

import os
import matplotlib.pyplot as plt
import numpy as np
import cv2
import pandas as pd
from tqdm import tqdm

import datasets
import monai
import pydicom

from datasets import load_dataset
from datasets import Dataset, DatasetDict, Image

from PIL import Image

from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Dropout, concatenate, Conv2DTranspose
from tensorflow.keras.models import Model

from keras.layers import BatchNormalization, Activation, Dense, Dropout
from keras.layers import Lambda, RepeatVector, Reshape
from keras.layers import Conv2D, Conv2DTranspose
from keras.layers import MaxPooling2D, GlobalMaxPool2D
from keras.layers import concatenate, add
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from skimage.transform import resize

import transformers
from transformers import SamModel
from transformers import SamProcessor

import torch
from torch import nn

import argparse

"""## Load arguements """

"""#ARGUMENTS NEEDED:

    token: your own Hugging Face access token (set via $HF_TOKEN, do not hardcode)
    unet_weights: '<BASE_DIR>/Heart_MRI_model_weights/myocardium-unet-256.h5'
    model_name: "reddysh/finetuned-myocardium-medSAM"
    image_path: "<BASE_DIR>/Heart_MRI/filtered-test-ShMOLLI-pngimages/"

    """
ap = argparse.ArgumentParser()

ap.add_argument("-t", "--token", required=True,
        help="token of private hugging face repo, where finetuned transformer model is located")
ap.add_argument("-uw", "--unet_weights", required=True,
        help="path to .h file of unet weights, for autobounding box estimation")
ap.add_argument("-n", "--model_name", required=True,
        help="name of the finetuned transformer model")
ap.add_argument("-i", "--image_path", required=True,
        help="path to input image(s), requires images in png format")
ap.add_argument("-o", "--output_path", required=True,
        help="path to output directory, will save a statistics.txt, mean_T1.csv, and mask_array directory")


args = vars(ap.parse_args())

token = args["token"]
unet_weights = args["unet_weights"]
model_name = args["model_name"]
image_path = args["image_path"]
output_path = args["output_path"]

os.environ["HF_HOME"] = "./"
os.environ["HF_TOKEN"] = token

"""## Load dataset """

def create_dataset(image_paths):
    dataset = Dataset.from_dict({"image": sorted(image_paths)})
    dataset = dataset.cast_column("image", Image())

    return dataset

"""# Define Bounding Boxes"""

def get_bounding_box(ground_truth_map):
  # get bounding box from mask
  y_indices, x_indices = np.where(ground_truth_map > 0)
  try:
      x_min, x_max = np.min(x_indices), np.max(x_indices)
  except:
      x_min = 0
      x_max = 255

  try:
      y_min, y_max = np.min(y_indices), np.max(y_indices)
  except:
      y_min = 0
      y_max = 255

  # add perturbation to bounding box coordinates
  H, W = ground_truth_map.shape
  x_min = max(0, x_min - np.random.randint(5, 10))
  x_max = min(W, x_max + np.random.randint(5, 10))
  y_min = max(0, y_min - np.random.randint(5, 10))
  y_max = min(H, y_max + np.random.randint(5, 10))
  bbox = [x_min, y_min, x_max, y_max]

  return bbox

# Convert image to grayscale and rescale from PNG to DICOM format for uNET preprocessing

def rgb2gray(rgb):
    gray = np.dot(rgb[...,:3], [0.299, 0.587, 0.114])
    gray = np.expand_dims(gray, axis=2)
    return gray

def convert_to_grayscale(sample):
    sample_array = np.array(sample["image"])

    # Convert the image to grayscale using the rgb2gray function
    gray_array = rgb2gray(sample_array)

    #Rescale array to dicom range
    dicom_range = 4000
    png_range = 255

    scaled_gray_array = gray_array * (dicom_range/ png_range)

    sample["image"] = np.array(scaled_gray_array)
    #print(sample["image"].shape)

    return sample

# Function to fully preprocess a PNG image datatype
def preprocess_grayscale(sample):
    sample_array = np.array(sample)

    # Convert the image to grayscale using the rgb2gray function
    gray_array = rgb2gray(sample_array)

    #Rescale array to dicom range
    dicom_range = 4000
    png_range = 255

    scaled_gray_array = gray_array * (dicom_range/ png_range)

    sample = np.array(scaled_gray_array)
    #print(sample["image"].shape)

    return sample

"""##Load the Unet"""

#Define a UNet and apply the pretrained weights

def conv2d_block(input_tensor, n_filters, kernel_size = 3, batchnorm = True):
    """Function to add 2 convolutional layers with the parameters passed to it"""
    # first layer
    x = Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),\
              kernel_initializer = 'he_normal', padding = 'same')(input_tensor)
    if batchnorm:
        x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # second layer
    x = Conv2D(filters = n_filters, kernel_size = (kernel_size, kernel_size),\
              kernel_initializer = 'he_normal', padding = 'same')(input_tensor)
    if batchnorm:
        x = BatchNormalization()(x)
    x = Activation('relu')(x)

    return x

def get_unet(input_img, n_filters = 16, dropout = 0.1, batchnorm = True):
    """Function to define the UNET Model"""
    # Contracting Path
    c1 = conv2d_block(input_img, n_filters * 1, kernel_size = 3, batchnorm = batchnorm)
    p1 = MaxPooling2D((2, 2))(c1)
    p1 = Dropout(dropout)(p1)

    c2 = conv2d_block(p1, n_filters * 2, kernel_size = 3, batchnorm = batchnorm)
    p2 = MaxPooling2D((2, 2))(c2)
    p2 = Dropout(dropout)(p2)

    c3 = conv2d_block(p2, n_filters * 4, kernel_size = 3, batchnorm = batchnorm)
    p3 = MaxPooling2D((2, 2))(c3)
    p3 = Dropout(dropout)(p3)

    c4 = conv2d_block(p3, n_filters * 8, kernel_size = 3, batchnorm = batchnorm)
    p4 = MaxPooling2D((2, 2))(c4)
    p4 = Dropout(dropout)(p4)

    c5 = conv2d_block(p4, n_filters = n_filters * 16, kernel_size = 3, batchnorm = batchnorm)

    # Expansive Path
    u6 = Conv2DTranspose(n_filters * 8, (3, 3), strides = (2, 2), padding = 'same')(c5)
    u6 = concatenate([u6, c4])
    u6 = Dropout(dropout)(u6)
    c6 = conv2d_block(u6, n_filters * 8, kernel_size = 3, batchnorm = batchnorm)

    u7 = Conv2DTranspose(n_filters * 4, (3, 3), strides = (2, 2), padding = 'same')(c6)
    u7 = concatenate([u7, c3])
    u7 = Dropout(dropout)(u7)
    c7 = conv2d_block(u7, n_filters * 4, kernel_size = 3, batchnorm = batchnorm)

    u8 = Conv2DTranspose(n_filters * 2, (3, 3), strides = (2, 2), padding = 'same')(c7)
    u8 = concatenate([u8, c2])
    u8 = Dropout(dropout)(u8)
    c8 = conv2d_block(u8, n_filters * 2, kernel_size = 3, batchnorm = batchnorm)

    u9 = Conv2DTranspose(n_filters * 1, (3, 3), strides = (2, 2), padding = 'same')(c8)
    u9 = concatenate([u9, c1])
    u9 = Dropout(dropout)(u9)
    c9 = conv2d_block(u9, n_filters * 1, kernel_size = 3, batchnorm = batchnorm)

    outputs = Conv2D(1, (1, 1), activation='sigmoid')(c9)
    model = Model(inputs=[input_img], outputs=[outputs])

    return model

input_img = Input((256, 256, 1), name='img')
unet_model = get_unet(input_img, n_filters=16, dropout=0.05, batchnorm=True)

unet_model.load_weights(unet_weights)

def remove_blobs(image, min_blob_size):

  # Find contours in the binary image
  contours, _ = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

  # Filter contours based on blob size and remove them
  filtered_contours = [cnt for cnt in contours if cv2.contourArea(cnt) < min_blob_size]

  # Create a mask of the filtered contours
  mask = np.zeros_like(image)
  cv2.drawContours(mask, filtered_contours, -1, 255, thickness=cv2.FILLED)

  # Invert the mask
  mask = 255 - mask

  # Apply the mask to the original image to remove the blobs
  result = cv2.bitwise_and(image, image, mask=mask)

  return result

def post_processing(prediction):

  # Define the structuring element and apply erosion
  kernel = np.ones((3, 3), np.uint8)

  eroded_mask = cv2.erode(prediction, kernel, iterations=1)
  blurred_mask = cv2.GaussianBlur(eroded_mask, (3, 3), 0)

  blurred_mask = (blurred_mask > 0.95).astype(np.uint8)
  blurred_mask = remove_blobs(blurred_mask, 120)

  # Update binary_preds with the transformed mask
  processed_pred = blurred_mask

  return processed_pred

def get_estimated_mask(input_img, unet_model):

    predicted_mask = unet_model.predict(np.expand_dims(input_img, axis=0))
    predicted_mask = post_processing(predicted_mask[0])

    return predicted_mask


"""## Load the SAM model

Stored on private HuggingFace repository
"""

processor = SamProcessor.from_pretrained("facebook/sam-vit-base")

model = SamModel.from_pretrained(model_name)

# make sure we only compute gradients for mask decoder
for name, param in model.named_parameters():
  if name.startswith("vision_encoder") or name.startswith("prompt_encoder"):
    param.requires_grad_(False)

# Check if CUDA is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Move the model to the device
model.to(device)
model.eval()

"""#Execution of Model"""

#Function to create predictions based on the inputs

def display_results(image, ground_truth, pred_seg):

  # Create subplots
  fig, axes = plt.subplots(1, 3, figsize=(10, 5))

  # Display first image and predicted mask
  axes[0].imshow(np.array(image))
  show_mask(ground_truth, axes[0])
  axes[0].set_title("Ground Truth")
  axes[0].axis("off")

  # Display second image and predicted mask
  axes[1].imshow(np.array(image))
  show_mask(pred_seg, axes[1])
  axes[1].set_title("Prediction")
  axes[1].axis("off")

  # AUTOBOUNDING BOX LOGIC:

  # # 1) use uNet to predict rough mask
  rough_image = preprocess_grayscale(image)
  estimated_mask = get_estimated_mask(rough_image, unet_model)

  # 2) create a bounding box out of the rough mask
  prompt = get_bounding_box(estimated_mask)

  # Show bounding box on the third image
  axes[2].imshow(np.array(image))
  show_box(prompt, axes[2])
  axes[2].set_title('Prompt Bounding Box')
  axes[2].axis('off')

  plt.show()

def predict(image):

  # AUTOBOUNDING BOX LOGIC:

  # # 1) use uNet to predict rough mask
  rough_image = preprocess_grayscale(image)

  estimated_mask = get_estimated_mask(rough_image, unet_model)

  plt.imshow(np.array(estimated_mask))
  plt.show()

  # 2) create a bounding box out of the rough mask
  prompt = get_bounding_box(estimated_mask)

  # 3) replace "global_prompt" with the custom bounding box
  inputs = processor(images=image, input_boxes=[[prompt]], return_tensors="pt").to(device)

  with torch.no_grad():
      outputs = model(**inputs, multimask_output=False)

  pred_seg_prob = torch.sigmoid(outputs.pred_masks.squeeze(1))

  pred_seg_prob = pred_seg_prob.cpu().numpy().squeeze()
  pred_seg = (pred_seg_prob > 0.5).astype(np.uint8)

  return pred_seg

def dice_coefficient(prediction, ground_truth):
    intersection = np.logical_and(prediction, ground_truth)
    intersection = np.count_nonzero(intersection)

    union = np.count_nonzero(prediction) + np.count_nonzero(ground_truth)

    dice = (2 * intersection) / (union)  # Add a small value to avoid division by zero
    return dice

def get_mean_T1(image, ROI):
  image = np.array(image)
  image = np.dot(image[...,:3], [0.299, 0.587, 0.114])

  ROI = np.array(ROI)

  mean_T1_ROI = ROI * image
  print(np.max(mean_T1_ROI))

  mean_T1_ROI = mean_T1_ROI * (4000/255)

  mean_T1_value = np.sum(mean_T1_ROI)/np.sum(ROI)

  return mean_T1_ROI, mean_T1_value

def calculate_statistics(values):
  ROI_T1_values = values[values != 0]

  std_dev_t1 = np.std(ROI_T1_values)
  percentile_99 = np.percentile(ROI_T1_values, 99)
  percentile_75 = np.percentile(ROI_T1_values, 75)
  percentile_50 = np.percentile(ROI_T1_values, 50)  # Median

  return std_dev_t1, percentile_99, percentile_75, percentile_50

""" Complete Workflow """

def process_dicom_files(image_dir, output_dir):
    
    #Ensure the SAM-masks directory exists
    mask_output_dir = os.path.join(output_dir, "SAM_masks")
    os.makedirs(mask_output_dir, exist_ok=True)
    
    # Define the output CSV file path
    output_csv_path = os.path.join(output_dir, "mean_T1.csv")
    processed_files_path = os.path.join(output_dir, "processed_files.txt")

    # Create the CSV file with headers if it doesn't exist
    if not os.path.exists(output_csv_path):
        df = pd.DataFrame(columns=['Patient_ID', 'Mean_T1', 'T1_50th_Percentile', 'T1_Standard_Deviation', 'T1_99th_Percentile', 'T1_75th_Percentile'])
        df.to_csv(output_csv_path, index=False)

    # Create the processed_files.txt if it doesn't exist
    if not os.path.exists(processed_files_path):
        with open(processed_files_path, 'w') as file:
            pass  # Just to create the file


    # Read the list of processed files
    if os.path.exists(processed_files_path):
        with open(processed_files_path, 'r') as file:
            processed_files = set(file.read().splitlines())
    else:
        processed_files = set()


    for filename in tqdm(os.listdir(image_dir)):
        
        if filename.endswith(".png") and filename not in processed_files:
            #Save patient ID
            patient_ID = os.path.splitext(os.path.basename(filename))[0]

            #Transform into Image type
            data = Image.open(os.path.join(image_dir, filename))
            image = data.resize((256, 256))

            #Get predicted mask
            prediction = predict(image)

            #Get mean_TI
            mean_T1_ROI, mean_T1 = get_mean_T1(image, prediction)

            # Calculate statistics
            std_dev_t1, percentile_99, percentile_75, percentile_50 = calculate_statistics(mean_T1_ROI)
               
            row_data = {
                'Patient_ID': patient_ID,
                'Mean_T1': mean_T1,
                'T1_50th_Percentile': percentile_50,
                'T1_Standard_Deviation': std_dev_t1,
                'T1_99th_Percentile': percentile_99,
                'T1_75th_Percentile': percentile_75
            }
            
            # Append the current row to the CSV file
            row_df = pd.DataFrame([row_data])
            row_df.to_csv(output_csv_path, mode='a', header=False, index=False)

            # Output mask with patient ID as filename
            mean_T1_ROI = Image.fromarray(mean_T1_ROI)
            mean_T1_ROI.save(os.path.join(mask_output_dir, f"{patient_ID}_mask.tiff"))

            # Append the filename to the processed files list
            with open(processed_files_path, 'a') as file:
                file.write(filename + '\n')

  
    
# Implement
process_dicom_files(image_path, output_path)
