"""Generates the fully synthetic example data used by demo/demo_walkthrough.ipynb.

Every value in demo/example_data/ is procedurally generated by this script with
a fixed random seed. Nothing here is derived from UK Biobank or any other
participant data. Re-running this script regenerates the committed files
byte-for-byte.

Imaging (T1 maps): centered at 960ms, matching the native-T1 range reported
for 1.5T ShMOLLI myocardial mapping (the manuscript's actual acquisition
protocol -- MAGNETOM Aera, 1.5T, ShMOLLI; see Piechnik et al. 2010, J.
Cardiovasc. Magn. Reson. 12, 69), not the ~1180ms placeholder used in an
earlier draft of this demo.
"""

import json
import os

import numpy as np
import pandas as pd

SEED = 42
N_SUBJECTS = 320
N_TRAIN_IMAGES = 40
IMAGE_SIZE = 256
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "example_data")

# 1.5T ShMOLLI native T1: ~950-970ms in normal myocardium (Piechnik et al. 2010).
T1_BASELINE_MS = 960.0


def make_t1_map(rng, disease_shift=0.0, radius_jitter=0.0, angle_jitter=0.0, noise_sd=5.0,
                 hotspot_angle=None, hotspot_width=0.5, hotspot_magnitude=0.0):
    """One synthetic full-field T1 map + annular myocardium mask, in milliseconds.

    The map includes non-zero background texture outside the myocardium (other
    simulated tissue/blood-pool signal), so that recovering the myocardium
    requires the mask rather than a trivial intensity threshold -- matching how
    the real pipeline isolates myocardium by multiplying the raw T1 map by its
    U-Net segmentation mask, rather than the map being pre-masked.

    `hotspot_angle` places a localized focal elevation (mimicking regional
    fibrosis) at a given angular position around the ring, so that different
    training subjects have genuinely different regional patterns rather than
    only a global intensity/gradient shift -- needed for the demo notebook's
    Grad-CAM section to show latent dimensions attending to different regions
    instead of all converging on the same whole-ring pattern.
    """
    coords = np.arange(IMAGE_SIZE, dtype=np.float32)
    yy, xx = np.meshgrid(coords, coords, indexing="ij")
    centre = np.float32((IMAGE_SIZE - 1) / 2)
    x_offset = xx - centre
    y_offset = yy - centre
    radius = np.sqrt(x_offset**2 + y_offset**2)
    angle = np.arctan2(y_offset, x_offset) + np.float32(angle_jitter)

    inner = np.float32(50.0 + radius_jitter)
    outer = np.float32(82.0 + radius_jitter)
    mask = (radius >= inner) & (radius <= outer)

    spatial_t1 = (
        np.float32(T1_BASELINE_MS + disease_shift)
        + np.float32(0.70) * x_offset
        + np.float32(0.35) * y_offset
        + np.float32(45.0) * np.cos(np.float32(3.0) * angle)
        + np.float32(22.0) * np.sin(radius / np.float32(8.0))
        + rng.normal(0, noise_sd, size=(IMAGE_SIZE, IMAGE_SIZE)).astype(np.float32)
    )

    if hotspot_angle is not None and hotspot_magnitude != 0.0:
        angular_diff = np.arctan2(np.sin(angle - hotspot_angle), np.cos(angle - hotspot_angle))
        spatial_t1 = spatial_t1 + np.float32(hotspot_magnitude) * np.exp(
            -(angular_diff ** 2) / np.float32(2 * hotspot_width ** 2)
        )

    # Background: blood pool / other tissue / air, on a distinctly different
    # intensity scale from myocardium, with its own smooth spatial texture.
    background = (
        np.float32(300.0)
        + np.float32(150.0) * np.exp(-((radius - np.float32(20.0)) ** 2) / np.float32(600.0))
        + np.float32(60.0) * np.sin(angle * np.float32(5.0))
        + rng.normal(0, 25.0, size=(IMAGE_SIZE, IMAGE_SIZE)).astype(np.float32)
    ).clip(0, None)

    t1_map = np.where(mask, spatial_t1, background).astype(np.float32)
    return t1_map, mask


def erode_mask(mask, iterations=8):
    """Binary erosion by a 3x3 cross structuring element, dependency-free."""
    eroded = mask.copy()
    for _ in range(iterations):
        shifted = (
            eroded
            & np.roll(eroded, 1, axis=0)
            & np.roll(eroded, -1, axis=0)
            & np.roll(eroded, 1, axis=1)
            & np.roll(eroded, -1, axis=1)
        )
        eroded = shifted
    return eroded


def compute_t1_phenotypes(t1_map, mask):
    values = t1_map[mask]
    percentiles = [0.25, 1, 25, 50, 75, 99, 99.75]
    out = {
        "Mean_T1": float(values.mean()),
        "T1_Standard_Deviation": float(values.std()),
    }
    for p in percentiles:
        label = f"T1_{p:g}th_Percentile"
        out[label] = float(np.percentile(values, p))
    return out


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    rng = np.random.default_rng(SEED)

    # --- Imaging: one canonical example + a small training set -------------
    canonical_t1, canonical_mask = make_t1_map(
        rng, hotspot_angle=np.pi / 3, hotspot_width=0.6, hotspot_magnitude=70.0
    )
    np.save(os.path.join(OUTPUT_DIR, "synthetic_t1_map_ms.npy"), canonical_t1)
    np.save(os.path.join(OUTPUT_DIR, "synthetic_myocardium_mask.npy"), canonical_mask)

    train_maps = np.zeros((N_TRAIN_IMAGES, IMAGE_SIZE, IMAGE_SIZE), dtype=np.float32)
    train_masks = np.zeros((N_TRAIN_IMAGES, IMAGE_SIZE, IMAGE_SIZE), dtype=bool)
    for i in range(N_TRAIN_IMAGES):
        disease_shift = rng.normal(0, 20.0)
        radius_jitter = rng.normal(0, 3.0)
        angle_jitter = rng.uniform(-0.2, 0.2)
        # Roughly a third of subjects get a localized focal hot spot at a
        # random angular position, giving the training set genuine regional
        # (not just global) variation between subjects.
        if rng.random() < 0.4:
            hotspot_angle = rng.uniform(-np.pi, np.pi)
            hotspot_width = rng.uniform(0.4, 0.8)
            hotspot_magnitude = rng.uniform(40.0, 90.0)
        else:
            hotspot_angle, hotspot_width, hotspot_magnitude = None, 0.5, 0.0
        t1_map, mask = make_t1_map(
            rng, disease_shift=disease_shift, radius_jitter=radius_jitter, angle_jitter=angle_jitter,
            hotspot_angle=hotspot_angle, hotspot_width=hotspot_width, hotspot_magnitude=hotspot_magnitude,
        )
        train_maps[i] = t1_map
        train_masks[i] = mask
    np.save(os.path.join(OUTPUT_DIR, "synthetic_t1_map_training_set.npy"), train_maps)
    np.save(os.path.join(OUTPUT_DIR, "synthetic_myocardium_mask_training_set.npy"), train_masks)

    # --- Genotypes + variant metadata (generated before the cohort table, so
    # variant 0's dosage can drive a designed genotype -> protein -> phenotype
    # chain below, giving the PWAS/GWAS/MR demo stages a real signal to find,
    # the same causal-inference shape the actual study's MR analysis targets) --
    subject_ids = [f"SYNTHETIC_{i + 1:04d}" for i in range(N_SUBJECTS)]
    n_variants = 24
    variant_ids = [f"SYNTH_chr1_{100000 + 1000 * i}_A_G" for i in range(n_variants)]
    eaf = np.clip(rng.uniform(0.10, 0.42, n_variants), 0.05, 0.5)
    genotypes = np.stack(
        [rng.binomial(2, freq, N_SUBJECTS) for freq in eaf], axis=1
    )
    genotypes_df = pd.DataFrame(genotypes, columns=variant_ids)
    genotypes_df.insert(0, "Synthetic_ID", subject_ids)
    genotypes_df.to_csv(os.path.join(OUTPUT_DIR, "synthetic_genotypes.tsv"), sep="\t", index=False)

    variant_metadata = pd.DataFrame(
        {
            "Variant": variant_ids,
            "Effect_Allele": ["G"] * n_variants,
            "Other_Allele": ["A"] * n_variants,
            "Effect_Allele_Frequency": eaf,
        }
    )
    variant_metadata.to_csv(
        os.path.join(OUTPUT_DIR, "synthetic_variant_metadata.tsv"), sep="\t", index=False
    )

    # --- Proteomics: 12 proteins, one designed genotype -> protein link -------
    n_proteins = 12
    protein_ids = [f"SYNTH_PROT_{i:02d}" for i in range(n_proteins)]
    proteomics = rng.normal(0, 1, size=(N_SUBJECTS, n_proteins))
    # SYNTH_PROT_00 is partly driven by variant 0's dosage, giving the demo
    # GWAS/PWAS/MR/colocalization stages a shared genotype -> protein ->
    # phenotype signal to detect (see Mean_T1 below), the same
    # causal-inference shape the real study's MR analysis targets.
    dosage_0 = genotypes[:, 0].astype(float)
    dosage_0_z = (dosage_0 - dosage_0.mean()) / dosage_0.std()
    proteomics[:, 0] = 0.6 * dosage_0_z + rng.normal(0, 0.8, N_SUBJECTS)
    proteomics_df = pd.DataFrame(proteomics, columns=protein_ids)
    proteomics_df.insert(0, "Synthetic_ID", subject_ids)
    proteomics_df.to_csv(os.path.join(OUTPUT_DIR, "synthetic_proteomics.tsv"), sep="\t", index=False)

    # --- Cohort table ----------------------------------------------------------
    age = rng.normal(64.0, 7.7, N_SUBJECTS).clip(45, 80)
    sex = rng.integers(0, 2, N_SUBJECTS)
    pc1 = rng.normal(0, 1, N_SUBJECTS)
    pc2 = rng.normal(0, 1, N_SUBJECTS)

    disease_liability = rng.normal(0, 1, N_SUBJECTS) + 0.02 * (age - 64.0)
    synthetic_disease = (disease_liability > np.percentile(disease_liability, 75)).astype(int)

    # Mean T1 elevated by disease status, mildly by age, and by SYNTH_PROT_00
    # (itself partly genotype-driven, above), centered at the 1.5T ShMOLLI
    # baseline.
    mean_t1 = (
        T1_BASELINE_MS
        + 40.0 * synthetic_disease
        + 0.5 * (age - 64.0)
        + 12.0 * proteomics[:, 0]
        + rng.normal(0, 20.0, N_SUBJECTS)
    ).clip(880, 1120)
    t1_sd = (48.0 + 6.0 * synthetic_disease + rng.normal(0, 3.5, N_SUBJECTS)).clip(30, 70)

    percentile_offsets = {
        "T1_0.25th_Percentile": -1.75,
        "T1_1th_Percentile": -1.4,
        "T1_25th_Percentile": -0.68,
        "T1_50th_Percentile": 0.0,
        "T1_75th_Percentile": 0.68,
        "T1_99th_Percentile": 1.4,
        "T1_99.75th_Percentile": 1.75,
    }

    event_liability = (
        0.03 * (mean_t1 - T1_BASELINE_MS) + 0.05 * (age - 64.0) + rng.normal(0, 3.0, N_SUBJECTS)
    )
    follow_up = rng.uniform(0.1, 14.0, N_SUBJECTS)
    event = (event_liability > np.percentile(event_liability, 60)).astype(int)

    cohort = pd.DataFrame(
        {
            "Synthetic_ID": subject_ids,
            "Age": age,
            "Sex": sex,
            "PC1": pc1,
            "PC2": pc2,
            "Mean_T1": mean_t1,
            "T1_Standard_Deviation": t1_sd,
            "Synthetic_Disease": synthetic_disease,
            "Follow_up_years": follow_up,
            "Event": event,
        }
    )
    for label, z in percentile_offsets.items():
        cohort[label] = mean_t1 + z * t1_sd
    cohort.to_csv(os.path.join(OUTPUT_DIR, "synthetic_cohort.tsv"), sep="\t", index=False)

    # --- Latent (VAE) phenotypes: 16 dims, standardized -----------------------
    n_latent = 16
    latent = rng.normal(0, 1, size=(N_SUBJECTS, n_latent))
    latent_cols = [f"Latent_{i}" for i in range(n_latent)]
    latent_df = pd.DataFrame(latent, columns=latent_cols)
    latent_df.insert(0, "Synthetic_ID", subject_ids)
    latent_df.to_csv(
        os.path.join(OUTPUT_DIR, "synthetic_latent_phenotypes.tsv"), sep="\t", index=False
    )

    # --- Checksums -------------------------------------------------------------
    import hashlib

    generated_files = sorted(
        f
        for f in os.listdir(OUTPUT_DIR)
        if f not in ("SHA256SUMS.txt", "README.md")
    )
    with open(os.path.join(OUTPUT_DIR, "SHA256SUMS.txt"), "w") as f:
        for fname in generated_files:
            path = os.path.join(OUTPUT_DIR, fname)
            digest = hashlib.sha256(open(path, "rb").read()).hexdigest()
            f.write(f"{digest}  {fname}\n")

    print(f"Wrote {len(generated_files)} synthetic data files to {OUTPUT_DIR}")
    print(f"Canonical T1 map: mean {canonical_t1[canonical_mask].mean():.1f}ms "
          f"(range {canonical_t1[canonical_mask].min():.1f}-{canonical_t1[canonical_mask].max():.1f}ms)")
    print(f"Cohort Mean_T1: {cohort['Mean_T1'].mean():.1f} +/- {cohort['Mean_T1'].std():.1f} ms")


if __name__ == "__main__":
    main()
